[22기 이원석] 검색 VIEW (test X)
wecode-bootcamp-korea/22-2nd-Oneted-backend pull request #16
Opened 2021-07-26 07:19 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 10:05 UTC, Kang-kyunghun commented
구두로 말씀드린 사항 반영해 주세요.

2021-07-27 01:15 UTC, wonseok2877 commented
앱 구조 수정했습니다!

2021-07-27 02:02 UTC, Kang-kyunghun commented
PR template 제대로 작성해 주세요.

2021-07-27 04:48 UTC, wonseok2877 commented
PR template 수정했습니다!

2021-07-27 06:03 UTC, Kang-kyunghun requested changes

2021-07-27 06:03 UTC, Kang-kyunghun commented on jobpostings/views.py
> +class SearchView(View):
```suggestion
class PostingsView(View):
```

2021-07-27 06:03 UTC, Kang-kyunghun commented on jobpostings/views.py
> +        job_postings     = JobPosting.objects.select_related("job", "experience", "company", "company__region", "company__region__country").annotate(bookmark_count=Count("bookmark"), apply_count=Coun
페이지네이셔 계산을 어떻게 하면 좋을지 다시 한 번 생각해 보세요.

2021-07-27 06:52 UTC, wonseok2877 commented on jobpostings/views.py
> +class SearchView(View):
수정완료했습니다!

2021-07-27 14:12 UTC, wonseok2877 commented on jobpostings/views.py
> +        job_postings     = JobPosting.objects.select_related("job", "experience", "company", "company__region", "company__region__country").annotate(bookmark_count=Count("bookmark"), apply_count=Coun
수정완료했습니다!

2021-07-27 14:17 UTC, wonseok2877 commented
질문 있습니다! 
필터링 가짓수가 8가지여서 각각의 가짓수를 모두 테스트해보려면 2의 8승... 256가지를 하는건 불가능하므로
일단 2개의 데이터에 상반된 데이터를 넣은 뒤에 query params 값에 따라서 둘 중 하나가 나오도록 만들었습니다!
이 정도면 충분한지 궁금합니다!

2021-07-28 01:20 UTC, Kang-kyunghun commented
LGTM

2021-07-28 01:20 UTC, merged