[22기 박성준][add] users_view (test x)
wecode-bootcamp-korea/22-2nd-Oneted-backend pull request #19
Opened 2021-07-26 07:39 UTC by SJPARK512

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 12:15 UTC, Kang-kyunghun requested changes

2021-07-26 12:15 UTC, Kang-kyunghun commented on users/views.py
> +        encoded_jwt = jwt.encode({"user_id": user.id}, SECRET_KEY, algorithm=ALGORITHM)
get_or_create로 바꿔보세요.

2021-07-26 12:15 UTC, Kang-kyunghun commented on users/views.py
> +        return JsonResponse({"user_info":user_info, "token":encoded_jwt}, status=201)
생성이 되었을 때와 안 되었을 때 공통으로 return을 사용하므로 200이 조그 더 적합할 것 같습니다.

2021-07-26 12:15 UTC, Kang-kyunghun commented on users/views.py
> +        job_posting = JobPosting.objects.get(id=jobposting_id)
1. = 기준으로 정렬
2. if와 exists()을 활용해서 존재 유무 판단해 주세요.

2021-07-26 12:15 UTC, Kang-kyunghun commented on users/views.py
> +        return JsonResponse({"Check": Bookmark.objects.filter(user=user, job_posting=job_posting).exists()}, status=201)
1. check로 True/False 주는 이유를 코멘트로 남겨주세요.
2. 삭제 후의 status 코드가 무엇이 좋을지 생각해 보세요.

2021-07-26 12:16 UTC, Kang-kyunghun commented
PR template 작성 안 하면 리뷰 진행 안 하겠습니다.

2021-07-27 09:21 UTC, SJPARK512 commented on users/views.py
> +        encoded_jwt = jwt.encode({"user_id": user.id}, SECRET_KEY, algorithm=ALGORITHM)
수정했습니다.

2021-07-27 09:21 UTC, SJPARK512 commented on users/views.py
> +        return JsonResponse({"user_info":user_info, "token":encoded_jwt}, status=201)
수정했습니다.

2021-07-27 09:21 UTC, SJPARK512 commented on users/views.py
> +        return JsonResponse({"Check": Bookmark.objects.filter(user=user, job_posting=job_posting).exists()}, status=201)
수정햇습니다.

2021-07-28 01:28 UTC, Kang-kyunghun requested changes

2021-07-28 01:28 UTC, Kang-kyunghun commented on users/views.py
> +            )
get_or_create을 사용할 때는 pk 같이 값이 변하지 않고, 데이터를 특정 지을 수 있는 것들로 가져와야합니다. 만약에 지금 넣은 속성 중 1개라도 다르면 완전히 다른 데이터로 취급합니다. 따라서 다음과 같이 작성해 주는 것이 좋습니다.
```suggestion
        users, is_created = User.objects.get_or_create(kakao_api_id  = user["id"])
        
        if is_created:          
            user.name          = user["kakao_account"]["profile"]["nickname"],
            user.email         = user["kakao_account"]["email"],
            user.profile_image = user["kakao_account"]["profile"]["profile_image_url"]
            user.save()
```

2021-07-28 06:17 UTC, SJPARK512 commented on users/views.py
> +            )
수정했습니다.

2021-07-28 06:57 UTC, Kang-kyunghun requested changes

2021-07-28 06:57 UTC, Kang-kyunghun commented on users/tests.py
> +class BookmarkTest(TestCase):
= 기준이 전체적으로 다 이상하네요. 수정해 주세요.

2021-07-28 06:57 UTC, Kang-kyunghun commented on users/tests.py
> +				}
인덴트 들어간게 이상한 것 같은데 확인해 보세요.

2021-07-28 06:57 UTC, Kang-kyunghun requested changes

2021-07-28 06:57 UTC, Kang-kyunghun commented on users/tests.py
> +from my_settings		import SECRET_KEY, ALGORITHM
import 기준으로 수정해 주세요.

2021-07-28 09:47 UTC, SJPARK512 commented on users/tests.py
> +from my_settings		import SECRET_KEY, ALGORITHM
수정했습니다.

2021-07-29 02:48 UTC, Kang-kyunghun commented
LGTM~!!

2021-07-29 02:49 UTC, merged