[22기 박성준][ADD] postings_view (posting 상세뷰 api 추가)
wecode-bootcamp-korea/22-2nd-Oneted-backend pull request #20
Opened 2021-07-26 08:04 UTC by SJPARK512

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
- posting 상세뷰 api 추가
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-26 10:05 UTC, Kang-kyunghun requested changes

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +        job_posting = JobPosting.objects.get(id=posting_id)
if와 exists()을 활용하여 포스팅의 존재 유무를 먼저 판단해 주세요.

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +        tags        = job_posting.tags.all()
굳이 변수에 안 담고 아래 for문에 바로 담아도 될 것 같습니다.

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +        job_posting_info={
```suggestion
        job_posting_info = {
```

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +            } for tag in tags]
```suggestion
            "tag_info"          : [{"name" : tag.name} for tag in tags]
```
그런데 이름만 줄꺼면 dictionary 말고 그냥 이름만 줘도 되지 않을까요?
```suggestion
            "tag_info"          : [tag.name for tag in tags]
```

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +
공백 제거해 주세요.

2021-07-26 10:05 UTC, Kang-kyunghun commented on utils.py
> +        print(request)
merge된 코드 rebase 하셨나요?

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +class PostingDetailView(View):
```suggestion
class PostingView(View):
```

2021-07-26 10:05 UTC, Kang-kyunghun commented on jobpostings/views.py
> +
공백은 1칸만 해주세요.

2021-07-26 10:51 UTC, SJPARK512 commented on jobpostings/views.py
> +        tags        = job_posting.tags.all()
수정했습니다.

2021-07-26 10:51 UTC, SJPARK512 commented on jobpostings/views.py
> +        job_posting_info={
수정 했습니다.

2021-07-26 10:51 UTC, SJPARK512 commented on jobpostings/views.py
> +            } for tag in tags]
수정 했습니다.

2021-07-26 10:52 UTC, SJPARK512 commented on utils.py
> +        print(request)
수정햇습니다.

2021-07-26 10:52 UTC, SJPARK512 commented on jobpostings/views.py
> +class PostingDetailView(View):
수정했습니다.

2021-07-26 10:52 UTC, SJPARK512 commented on jobpostings/views.py
> +
수정했습니다.

2021-07-26 12:17 UTC, Kang-kyunghun requested changes

2021-07-26 12:17 UTC, Kang-kyunghun commented on resumes/views.py
> +import boto3
해당 view 제거하고 다시 올리세요.

2021-07-27 01:05 UTC, Kang-kyunghun commented
리뷰 반영 제대로 안 되었고, commit도 3개입니다.
리뷰 다시 반영 하고, rebase해서 다시 올려주세요.

2021-07-27 01:54 UTC, SJPARK512 commented on resumes/views.py
> +import boto3
수정했습니다.

2021-07-29 02:53 UTC, Kang-kyunghun requested changes

2021-07-29 02:53 UTC, Kang-kyunghun commented on jobpostings/views.py
> +            return JsonResponse({"message" : "INVAID_POSTING"}, status=401)
데이터 없는 경우이므로 404 NOT_FOUND가 더 적절해 보입니다.

2021-07-29 02:53 UTC, Kang-kyunghun commented on jobpostings/views.py
> +        user        = request.user
```suggestion
        user = request.user
```
print 제거하고 = 간격 줄여 주세요.

2021-07-29 04:42 UTC, SJPARK512 commented on jobpostings/views.py
> +            return JsonResponse({"message" : "INVAID_POSTING"}, status=401)
수정했습니다.

2021-07-29 04:43 UTC, SJPARK512 commented on jobpostings/views.py
> +        user        = request.user
수정했습니다.

2021-07-29 06:57 UTC, Kang-kyunghun commented
LGTM~~!!

2021-07-29 06:57 UTC, merged