sagve
wecode-bootcamp-korea/22-2nd-Oneted-backend pull request #24
Opened 2021-07-27 04:29 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 특정 유저의 특정 이력서에 대한 상세 내용
		 
## 수정 사항들 자세한 내용
- headers : Authorization
- path params : resume_id
- get : 해당 id에 대한 이력서의 상세 정보

## 기타 질문 및 특이 사항
- 파일 이력서 버전(구현 시도중)일 때를 아직 구현 안 했음!

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-27 06:01 UTC, Kang-kyunghun requested changes

2021-07-27 06:01 UTC, Kang-kyunghun commented on resumes/views.py
> +                return JsonResponse({"message" : "USER_NOT_MATCH"}, status=401)
```suggestion  
            if Resume.objects.filter(id=resume_id, user=request.user).exists():
                return JsonResponse({"message" : "USER_NOT_MATCH"}, status=401)
            
            resume = Resume.objects.get(id=resume_id, user=request.user)
```
이력서가 특정 유저의 의존하고 있는 자원이기 때문에 유저와 같이 존재 여부를 판단하게 되면, 이력서의 존재 유무, 해당 유저의 이력인가의 대한 유무를 동시의 판단이 가능합니다.

2021-07-27 06:01 UTC, Kang-kyunghun commented on resumes/views.py
> +class ResumeDetailView(View):
```suggestion
class ResumeView(View):
```

2021-07-27 07:19 UTC, wonseok2877 commented on resumes/views.py
> +class ResumeDetailView(View):
수정 완료했습니다!

2021-07-28 01:32 UTC, Kang-kyunghun requested changes

2021-07-28 01:32 UTC, Kang-kyunghun commented on resumes/views.py
> +                return JsonResponse({"message" : "USER_NOT_MATCH"}, status=401)
원하는 데이터가 없는 경우니까 NOT_FOUND가 더 적절해 보입니다. 
user가 일치하지 않는지, 아니면 이력서가 없는지가 아닌 해당 유저와 이력서 아이디가 일치하는 데이터가 없는 경우이기 때문입니다.

2021-07-28 01:32 UTC, Kang-kyunghun commented on resumes/views.py
> +            resume = Resume.objects.get(id=resume_id)
위와 같은 이유로 get을 할 때 user 정보도 같이 입력해 주셔야 합니다.
```suggestion
            resume = Resume.objects.get(id=resume_id, user=request.user)
```

2021-07-28 01:32 UTC, Kang-kyunghun commented on resumes/views.py
> +            return JsonResponse({"message" : "RESUME_NOT_EXIST"}, status=401)
위의 리뷰 사항을 반영하면 필요 없는 예외처리가 될 것 같습니다.

2021-07-28 01:53 UTC, wonseok2877 commented on resumes/views.py
> +                return JsonResponse({"message" : "USER_NOT_MATCH"}, status=401)
넵! 수정완료했습니다!

2021-07-28 01:54 UTC, wonseok2877 commented on resumes/views.py
> +                return JsonResponse({"message" : "USER_NOT_MATCH"}, status=401)
넵! 수정완료했습니다!

2021-07-28 01:54 UTC, wonseok2877 commented on resumes/views.py
> +            resume = Resume.objects.get(id=resume_id)
, user=request.user

2021-07-28 01:55 UTC, wonseok2877 commented on resumes/views.py
> +            return JsonResponse({"message" : "RESUME_NOT_EXIST"}, status=401)
넵! 수정완료했습니다!

2021-07-28 05:20 UTC, Kang-kyunghun requested changes

2021-07-28 05:20 UTC, Kang-kyunghun commented on resumes/views.py
> +        print(request)
print 제거해 주세요.

2021-07-28 05:20 UTC, Kang-kyunghun commented on resumes/tests.py
> +        print(response.json())
print 제거해 주세요.

2021-07-28 06:21 UTC, wonseok2877 commented on resumes/tests.py
> +        print(response.json())
넵! 수정 완료했습니다!

2021-07-28 06:21 UTC, wonseok2877 commented on resumes/views.py
> +        print(request)
넵! 수정 완료했습니다!

2021-07-28 06:58 UTC, Kang-kyunghun commented
LGTM

2021-07-28 06:58 UTC, merged