[22기 이원석] 이력서 생성 VIEW
wecode-bootcamp-korea/22-2nd-Oneted-backend pull request #25
Opened 2021-07-27 04:55 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- 이력서 생성
		 
## 수정 사항들 자세한 내용
- headers : Authorization
- body : 이력서 내용
- create : 이력서 생성

## 기타 질문 및 특이 사항
- 파일 이력서 버전(구현 시도중) 아직 안 됌! 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.
- [x] 유닛 테스트를 구현 하였고 모든 유닛 테스트가 통과 된것을 확인 하였습니다.

2021-07-27 06:02 UTC, Kang-kyunghun requested changes

2021-07-27 06:02 UTC, Kang-kyunghun commented on resumes/views.py
> +                })
가독성 좋게 정렬해 주세요.

2021-07-27 07:28 UTC, wonseok2877 commented on resumes/views.py
> +                })
넵! 수정 완료했습니다!

2021-07-28 05:22 UTC, Kang-kyunghun requested changes

2021-07-28 05:22 UTC, Kang-kyunghun commented on resumes/views.py
> +            print("json fuck")
이건 뭘까요? 제거해 주세요.

2021-07-28 05:22 UTC, Kang-kyunghun commented on resumes/views.py
> +            print(data)
print 제거해 주세요.

2021-07-28 06:28 UTC, wonseok2877 commented on resumes/views.py
> +            print("json fuck")
죄송합니다.. 수정했습니다!

2021-07-28 06:28 UTC, wonseok2877 commented on resumes/views.py
> +            print(data)
넵! 수정했습니다!

2021-07-28 07:28 UTC, Kang-kyunghun commented
LGTM~~!

2021-07-28 07:28 UTC, merged